name: Deploy n8n

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            # Остановить n8n, если он запущен
            pm2 stop n8n || true
            
            # Если директория не существует, создать её и клонировать репозиторий
            if [ ! -d '/opt/n8n' ]; then
              mkdir -p /opt/n8n
              cd /opt
              git clone https://github.com/${{ github.repository }}.git n8n
            else
              # Иначе просто обновить репозиторий
              cd /opt/n8n
              git pull
            fi
            
            # Установить зависимости
            cd /opt/n8n
            npm install
            
            # Запустить n8n через PM2
            pm2 start npm --name \"n8n\" -- start || pm2 restart n8n
            pm2 save
          "
